language: clojure
lein: lein2
script: lein2 uberjar
sudo: false
branches:
  only:
  - staging
cache:
  directories:
  - $HOME/.m2
before_install:
- openssl aes-256-cbc -K $encrypted_134e2e7eeaf1_key -iv $encrypted_134e2e7eeaf1_iv
  -in id_rsa.enc -out .travis/id_rsa -d
after_success:
- if [ "$TRAVIS_BRANCH" == "staging" ]; then export APP="export-server-stg"; fi
- echo "Deploying to $SERVER"
- cp .travis/known_hosts ~/.ssh/known_hosts
- chmod 600 ~/.ssh/known_hosts
- chmod 600 .travis/id_rsa
- chmod 600 .travis/id_rsa.pub
- ssh-add .travis/id_rsa
- scp -i .travis/id_rsa target/export-server-1.2.2-standalone.jar root@104.236.66.244:/apps/$APP/export-server-1.2.2-standalone.jar
notifications:
  slack: anychart-team:sJRPhNn8Ur8yVdhvhgp6EbDM

